### ISSUE TITLE
disallowed_useragent

### ISSUE THREAD

**Issue by piotrros** [ConfusedVorlon/HSGoogleDrivePicker#4]
Hi,
I'm no longer able to use your library. I'm getting following error:

Error: disallowed_useragent

Here's some research:
http://stackoverflow.com/questions/40591090/403-error-thats-an-error-error-disallowed-useragent
http://stackoverflow.com/questions/40654403/403-error-disallowed-useragent

Looks like it's not possible to use google apis while using web application credentials. 
Is it hard to switch to ios client outh instead?

Regards

**Comment by ConfusedVorlon** [comment]
thanks for the report - i'll investigate when I get some time!
Google is such a pain to work with...

in the meantime, if you figure it out, then a pull request would be welcomed

**Comment by ConfusedVorlon** [comment]
this should be fixed with 2.0

note that the API is slightly changed, and you now need to do some more work in your app delegate to support the sign-in flow.
