### ISSUE TITLE
sign-in shows twice in iOS8

### ISSUE THREAD

**Issue by ConfusedVorlon** [ConfusedVorlon/HSGoogleDrivePicker#7]
open picker
sign in
click allow
signin view disappears

expected:
everything is splended

actual: 
signin view shows again

**Comment by maheshcheliya** [comment]
you got any solution for this issue ?

**Comment by ConfusedVorlon** [comment]
sorry - I haven't looked at it. You're welcome to send a pull request.

**Comment by maheshcheliya** [comment]
in HSDriveFileViewer.m, **viewDidAppear** method called before **didSignInForUser** after successfully sign in.

**Comment by ConfusedVorlon** [comment]
fixed in 2.1.0
