### ISSUE TITLE
Picker is loaded empty 

### ISSUE THREAD

**Issue by sushmithsreenivas** [ConfusedVorlon/HSGoogleDrivePicker#9]
When I downloaded and run your code after all the instructions , its working but when I implement in my actual project I get an empty picker .I don't get any crashes and I don't get a way to solve this problem

**Comment by ConfusedVorlon** [comment]
sounds like you need to dig deeper to figure out why your project is different to the demo.

Make sure you have implemented the app delegate, and if you have, you'll have to dig in to the networking to see what is being returned, and whether it is populating the table correctly.

If you can pin down a specific bug, I'll be happy to re-open this.
